"""pptxboss: read, verify and create PowerPoint (.pptx) decks with a clean-room Rust engine."""

from pptxboss import write
from pptxboss._pptxboss import (
    AppProperties,
    Chart,
    ChartSeries,
    Comment,
    CoreProperties,
    Diagram,
    Document,
    EmbeddedObject,
    Finding,
    Image,
    PptxError,
    Rule,
    Section,
    Shape,
    Slide,
    SlideIter,
    __version__,
    check,
    rules,
)

__all__ = [
    "AppProperties",
    "Chart",
    "ChartSeries",
    "Comment",
    "CoreProperties",
    "Diagram",
    "Document",
    "EmbeddedObject",
    "Finding",
    "Image",
    "PptxError",
    "Rule",
    "Section",
    "Shape",
    "Slide",
    "SlideIter",
    "__version__",
    "check",
    "rules",
    "write",
]
