from collections.abc import Iterator
from os import PathLike

__version__: str

class PptxError(Exception):
    """Raised for any PowerPoint processing error (bad data, unreadable parts, I/O)."""

class Document:
    """An open presentation. Thread-safe; heavy calls release the GIL."""

    def __init__(self, path: str | PathLike[str] | None = None, *, data: bytes | None = None) -> None: ...
    @property
    def slide_count(self) -> int: ...
    @property
    def path(self) -> str | None: ...
    @property
    def presentation_part(self) -> str: ...
    @property
    def slide_size(self) -> tuple[int, int] | None: ...
    @property
    def slide_size_type(self) -> str | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Slide: ...
    def __iter__(self) -> SlideIter: ...
    def slide(self, index: int) -> Slide: ...
    def slides(self) -> list[Slide]: ...
    def text(self, *, notes: bool = False, furniture: bool = False, hidden_shapes: bool = False, hidden_slides: bool = True) -> str: ...
    def text_reporting(self, *, notes: bool = False, furniture: bool = False, hidden_shapes: bool = False, hidden_slides: bool = True) -> tuple[str, list[str]]: ...
    def slide_texts(self, *, notes: bool = False, furniture: bool = False, hidden_shapes: bool = False, hidden_slides: bool = True) -> list[str]: ...
    def titles(self) -> list[str | None]: ...

class SlideIter(Iterator[Slide]):
    def __iter__(self) -> SlideIter: ...
    def __next__(self) -> Slide: ...

class Slide:
    """One parsed slide."""

    @property
    def index(self) -> int: ...
    @property
    def number(self) -> int: ...
    @property
    def part(self) -> str: ...
    @property
    def hidden(self) -> bool: ...
    @property
    def name(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def warnings(self) -> list[str]: ...
    def text(self, *, furniture: bool = False, hidden_shapes: bool = False) -> str: ...
    def paragraphs(self) -> list[str]: ...
    def notes(self) -> str | None: ...
    def tables(self) -> list[list[list[str]]]: ...
    def shapes(self) -> list[Shape]: ...
    def images(self) -> list[Image]: ...
    def image_bytes(self, image: Image) -> bytes: ...
    def hyperlink(self, rel_id: str) -> str | None: ...

class Shape:
    """One node of a slide's shape tree."""

    id: int
    name: str
    kind: str
    hidden: bool
    placeholder: str | None
    placeholder_index: int | None
    text: str | None
    description: str | None
    hyperlink: str | None
    frame: tuple[int, int, int, int] | None
    rotation: int
    image_rel: str | None
    rows: list[list[str]] | None
    children: list[Shape]
    @property
    def is_title(self) -> bool: ...

class Image:
    """An image referenced from a slide."""

    shape_id: int
    rel_id: str
    part: str | None
    content_type: str | None
    external: str | None
