"""Shared fixtures: the tiny decks under tests/fixtures, generated by the Rust testkit."""

from pathlib import Path

import pytest

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def minimal_pptx() -> Path:
    return FIXTURES / "minimal.pptx"


@pytest.fixture
def three_slides_pptx() -> Path:
    return FIXTURES / "three-slides.pptx"


@pytest.fixture
def shapes_pptx() -> Path:
    return FIXTURES / "shapes.pptx"


@pytest.fixture
def features_pptx() -> Path:
    return FIXTURES / "features.pptx"


@pytest.fixture
def legacy_ppt() -> Path:
    return FIXTURES / "legacy.ppt"
